### ISSUE TITLE
Start window checkbox incorrectly colored + start window too large

### ISSUE THREAD

**Issue by electrovoyage** [Areng14/BeePackageEditor#3]
Title. I just downloaded the software to take a look, and noticed that the checkbox looks wrong when clicked.
![image](https://github.com/Areng14/BeePackageEditor/assets/75689188/6112c71e-a88e-4fb9-a7e5-cec25aa1bbba)
Also its insides are white when not clicked. There's a parameter for this, i think it's called `selectbackground`?
![image](https://github.com/Areng14/BeePackageEditor/assets/75689188/21a22a8e-7459-44a1-bc90-eb67c5241b2b)
Also the window looks way too large.
![image](https://github.com/Areng14/BeePackageEditor/assets/75689188/904f7f95-32c3-4fe3-b854-885f77096844)

**Comment by Areng14** [comment]
Il go check it out

**Comment by Areng14** [comment]
Fixed
